apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:E/eKroNIFGiA6aT2rdF3/1ct2jk/wbFc83JCcgk3jFnXevBS,iv:JZ5X1Kg4Lh3s/Qp838JwaDVeQ0N3myPg4P8kg0Cr3YM=,tag:Z0Vfde2FHAupUhSWbMwP2g==,type:str]
    credentials.json: ENC[AES256_GCM,data:X6AnQg8MaoeFy/pdDw/V9P+U+Mvoh05nBOxdDE1KDdDKWxN2S3D087dgO47BBaWP/kyiEK0DOCQfI+XILbKB4e6Epf5CQuT2UddTX/HAfckbV/TQNMnqjKfcuJcZWHztuJlZrjTzgCCez97j6n7VseyXtAzmp++FWD86LAeisW+IWBt6vpjevsQkZ8hcMKIGhmnPNyrHs6VKQCjnfOWATGyU1tzIWAfF5YCOjpo5Sw==,iv:73W18XFqENbfN0GiGooHTCkO0/53S77dzEwfYVxggII=,tag:hQ5VVv6DuZMV3+fBdR20nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQURRYnhBUVBtR1J3ZWZv
            bi9LeUtFL0FDTzlQTG9VWDNUZURJQXlOZmhvCk4rT1ZzVFFGUnk5cnZBMEZManNF
            ZUZzSWFQanVKQ0V2MjVmUUJUS2xhbFEKLS0tIFpnRHNrRHRiT2dBT056QTBiNmpF
            eXdHNHNDREd3RWZ2c2FTOStVMStoL28KLlfRWUBPy4g/UO1FYzjoM+i524os/KPn
            YCDlIlANa9/yCYc3nGgJi+PZ5KNSUV69n0/yuLVywvSQ7MmyUVXQHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T03:06:12Z"
    mac: ENC[AES256_GCM,data:vhUnzHD1smj0+2voOc32veXlEbNx/1ahADIozawHodA4pbpVZR/BlnTKqf75Qmb1uPSf2OfLU91ug+9GM3pWUjIiGwy1+mJK4c5+xNWCAUACXFF7Zh+AsThuWPtHNc4lxHd4s0mOXf5puKOp3qYH2ymi6I0bcgpSmIdqNGqnRMo=,iv:9zdUj8kfNPHRl1ZUKRfLqH88EU9zaXBZj1112vSU+TU=,tag:Ax4vxndjyv7zSRNSWzRyzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
