apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:hHR4Mh2kzVA94G/exXyMGVgXpLMcTm6HXGZPr6HS90FZwqY41NmS+A==,iv:N2V3IIM1KL9gP9nbFbWMElld3CEkB4x68Z2yjQe1MmY=,tag:M+CBlX9CShkt8cIF/xwpoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2g1ZkhOa2E5eVZSQjBr
            NG1iampMS3dsYXNmNFp2UDU3U2NCOERQRVZrCmxMOWhCOVFYRlY3NytON3gzKzFj
            WHRhQUVReXY5NHNQb3FhODBjUkZCRHcKLS0tIGVaLzFNTlMxS3NISXJHaW1mTG8r
            SUFWbzI2cC9EdHB6eHEzS05LTkVmNE0KnnQ2GUYneVLXILTlhGuMbKXL9r/yXbr+
            GDZ2D1lbUmV7Vrg6NEUmleaJEogSz4fCKlNUiR+r55i5BQMtQ8aOQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T15:45:25Z"
    mac: ENC[AES256_GCM,data:8NPiWb3p8rSOzSMXu/k2G/cpcxZdN8Nfrku4jPFb4CiQwIztnKBimSFqvlsD1TiP2YjbD7pZgP7SvD+YSY+noCB2Pn6TV3AWjs+qi4k++vDfVeSwLVyv3ttxsKQi5ZAAqAXerp5Z4gEzpS2NbhjoVACdmcN0h98uCS+sEBwZHEw=,iv:TlXlB3hYmn5vvWuRUtpxH/1TSkXrzr2Zirappnz8oqA=,tag:Yz9l+abxIUzdV9flZgAJnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
