apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:mPo3XYjGdLID7x6PbSfBCxhPvywIicnIxdtNfvDxhwgAo6QBEqN+bg==,iv:PcHG00gFr/2xDDpZhxMZRIAVQ3GdoUYEwczHzVDEQx4=,tag:BQXROx2GkeKoT1CvLZonUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFpmL0tKaExCR2VqenRL
            Yms1RHkvdHlGUVpldVBlQk1ucjR3Qk5kcTJzCjY5ZlBIL0lxcU10SFhuNVEwOE1U
            VWR2MWtpYkJDNzEzVDRxNk5nQ1JBc0kKLS0tIHc3Y2N6d0RaQ1hsK3dKbURoenp1
            UVRzYUtqY2I0UWF2cFVwNkVWUndPTDQK5STjm6WuXV9kUMsgyMyxnmCl3cpQDBgj
            6eBUwatSrKwkYY+rVppaODPwNbEVIqOGjpEsMDPtpbMAc/yYEraiqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T03:06:12Z"
    mac: ENC[AES256_GCM,data:akV22R/daQzs/uLviSIbD5RGCYAi4K+pRagtGOkVsQ7+bj17AEoH/vnHeZn/FUQf//z4gdnPCorVf9Yl37hUnRa8Flg8uGPy/OYKEGajaTkxOLBu/NLOoSRVfYrolJK4O+irVFDV1HzIMWfqkoTr4mRMCijT5X8QtVF6WRk9PWw=,iv:hUY495MEMW7eO35kukx+0Uu4T9UqWSDHf79LEu440Xc=,tag:xT5HZYG409KX+/nc8J35Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
