---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-ftb-data-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 20Gi
