apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:1Kh3yTunvrGFDnrSfnYulTmIVO+uka6I2JRdgrkJab4=,iv:6Im2MTzetzVSVRO7syY+QIxHa1P9u5iPzp+NAO9bEAo=,tag:fMIoZS/u9Cdn+aYqcVu4gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWG4zVmQyR29SZGorTU5P
            Q1BPblVNSFJnV2ZYLzVEU05nYmVodnVMNEhjCjBFQkI4bll1MDMwT1hNYnpoYmdC
            NUVCMXdna3BFS0dEWG1wRlJWK2FiRzAKLS0tIFhNUUtqTm1FeWxpVG16OGF2dEl6
            bHdySmZOMkpIVVI1SGc1MVI3RlNSNjAKogDDeQrK7jZd/CY3BFD/AWs3dUz/a2T/
            LFkIl7Mbbxj242rTMCPSOyq0PuGCZLyR0zmgWlGjAXj358y+2YRVEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T06:14:29Z"
    mac: ENC[AES256_GCM,data:sFXrNITTs9kLV2TXjTy0It4ntwICgpLYx+UrXrhLg17/mNSEKVWRSq6z1a352K1FxCan9DG3P1860tqmnDa4QwO07IDXNm9Nz1egf4t6Sb4A0fSUyX9L4pnKh0xkRUL1ApjAn2knQTi6b0+kKxAYC+HIPR7/JgNf20B86BIUgTI=,iv:LlKwNMdKGLapsgUBQvW+J/mKVAt1+1xUTGDVkJ7gRwg=,tag:952dDkpVy5EInOrqtKTw4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
