apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wKWQzyJ9h6ywIM4RL3qzICwhAprwUHiJm3I+osHiwtA=,iv:o36KMDxMGGLV2kTbHYa7Vi2kJAF2/iSgVwAo3qG2Hno=,tag:2KyZ8Tzhd1GVU0EpgVOu6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReitpcU5ST2ZiTXhlcjcw
            a2lEcFZCWTNGVjNvbE10OS9aa0gzdjlENVRvCnVNZlltTUprQnlVYllBOU1RTU0w
            U1V3b25uMkFLMGlSQnZrTWI4TWxnazQKLS0tIGxReHljMU1iRVc4L2xNb1dVMVZX
            OEpmNEhvYzA2OW12aDFhZE92RjJsWWcKtr2NoWOkYL5mSebGiY7LJUZHQcpJg8wG
            kJAfm1RpUdAh5HceY0Uq8CXikN0syGV7MnlW/EfIzBAdRHCPgSTIdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T04:24:10Z"
    mac: ENC[AES256_GCM,data:Il+exrfWbq647RC3adbHFjwL+Mcysj6XPaOITlq28ssSOvIqSHYymFrMfgGqc+UrmnnhZiwWJsipuioD+gFCtgplQRYNJOnDTqOH9h6LmY1nlw00TR119x0NRvl0JsblqrOh9p179Clt+1SwGvTNCSukJlP0NDFb3LX6uV7tix4=,iv:XNj2n/MMPPz8/nsyZ+Rh6+rqIWAZU2UJZ0V7vsBsvcA=,tag:XCADR8cRMylwwqeunNTtug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
