apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:teGXOI0EoPE6bgmKMmwZMxOaziuRU1SyuE9DZRfV655ysRxTl3l6PA==,iv:7Zz3eRscf3RJWpg2x4KN9eMsjevZXNuP01Y5HJJemr4=,tag:Y0yPRTnNhY8ObTI3CfJ/kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWi9tdjgvU1NFR21oaXA2
            eFFYNURsZXozU1ZPQVpyTWxJbm5RQ0RLTFIwCjc1MDU3TjgvWjMwMXlRNytOZGwx
            dW10NC9BQUhlTmlUeWVLRkc3NnFYVzQKLS0tIEhiaXhMeDZ5RnM2ZHJkaUI3S1ls
            OEtlQzg4bHFvbEUvemJ1ZjlZQVkydnMKjhHXcLXlVj3AuP3k4bPPIFrk1ucxQV79
            mnGol2tAEXiOPc/IUYCdzQBpTqW7IeOoa9/t/plLuu/3uJ5nyorOtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T17:15:52Z"
    mac: ENC[AES256_GCM,data:Cw0b9PR+b6j/Pyth4jSnKNkIDAMpUj5mtIOwji5JsLNy6rPhusxbHsbtrrAlCzUEqOCuheDu8Ha6pkgvMA5iOGqldx5SSke7UJ1+eKkdco+f/kg19NFLy9PQ3z0wW2XCeXQPq8NxLj4m6Yw4fZ71ozhoV/TC59TTC5ucVDh+cBo=,iv:lvhXA0ZHOnB+/Q6Ss0rSlaR+jc0gv840pKl25czN07M=,tag:Pd2rSa41CYcSWLv+qHWzHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
